const sampleJobs = [
 {id:1,title:'Business Intelligence Analyst',company:'Northstar Finance',fit:94,ats:91,decision:'Apply',why:'Strong SQL, Power BI and reporting alignment. Add measurable dashboard outcomes before submission.',keywords:['SQL','Power BI','stakeholder reporting','data modelling']},
 {id:2,title:'Data Analyst',company:'Halo Health',fit:88,ats:86,decision:'Apply',why:'Good analytical fit with a clear mission match. Highlight healthcare data experience only if verified.',keywords:['Excel','SQL','Python','data quality']},
 {id:3,title:'Junior Analytics Engineer',company:'Mosaic Labs',fit:76,ats:72,decision:'Maybe',why:'Promising technical direction, but requires dbt and production data modelling evidence.',keywords:['dbt','SQL','Python','data modelling']}
];
const state={jobs:JSON.parse(localStorage.getItem('mojerryJobs')||'null')||sampleJobs,applications:JSON.parse(localStorage.getItem('mojerryApps')||'[]'),profile:JSON.parse(localStorage.getItem('mojerryProfile')||'{}')};
const $=s=>document.querySelector(s); const save=()=>{localStorage.setItem('mojerryJobs',JSON.stringify(state.jobs));localStorage.setItem('mojerryApps',JSON.stringify(state.applications));localStorage.setItem('mojerryProfile',JSON.stringify(state.profile))};
function nav(id){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.nav-item').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');document.querySelector(`[data-view="${id}"]`)?.classList.add('active');render()}
document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>nav(b.dataset.view));document.querySelectorAll('[data-view-target]').forEach(b=>b.onclick=()=>nav(b.dataset.viewTarget));
function fitClass(n){return n<80?'mid':''} function card(j){return `<article class="job-card" onclick="showDetail(${j.id})"><div class="card-top"><span class="company">${j.company}</span><span class="score ${fitClass(j.fit)}">${j.fit}% FIT</span></div><h3>${j.title}</h3><div class="card-foot"><span class="decision">${j.decision.toUpperCase()}</span><span>ATS ${j.ats}</span></div></article>`}
function render(){const priority=[...state.jobs].sort((a,b)=>b.fit-a.fit).slice(0,3);$('#priorityJobs').innerHTML=priority.map(card).join('');$('#jobCount').textContent=String(state.jobs.length).padStart(2,'0');$('#jobsTable').innerHTML=state.jobs.map(j=>`<tr><td class="role">${j.title}<small>${j.company}</small></td><td><span class="score ${fitClass(j.fit)}">${j.fit}%</span></td><td>${j.ats}</td><td><span class="badge ${j.decision==='Maybe'?'maybe':''}">${j.decision}</span></td><td><button class="link-btn" onclick="showDetail(${j.id})">Review →</button></td></tr>`).join('');$('#applicationsCount').textContent=state.applications.length;$('#metricApps').textContent=state.applications.length;$('#metricAts').textContent=state.applications.length?Math.round(state.applications.reduce((a,b)=>a+b.ats,0)/state.applications.length):'—';const empty=!state.applications.length;$('#applicationEmpty').classList.toggle('hidden',!empty);$('#applicationTable').classList.toggle('hidden',empty);$('#applicationsTable').innerHTML=state.applications.map(a=>`<tr><td class="role">${a.title}<small>${a.company}</small></td><td>${a.date}</td><td><span class="badge">Prepared</span></td><td>In 7 days</td></tr>`).join(''); const logs=[['09:42','Job Intelligence assessed '+state.jobs.length+' opportunities.'],['09:39','Truthful-only guardrail is active for all documents.'],['09:31',state.profile.headline?'Career profile loaded for tailoring.':'Waiting for career profile details.']];$('#activityLog').innerHTML=logs.map(l=>`<div class="log"><time>${l[0]}</time><span>${l[1]}</span></div>`).join('');if(state.profile.headline){$('#nextTitle').textContent='Review your top match';$('#nextText').textContent='The agent has ranked your strongest opportunity. Check the reasoning before preparing an application.'}}
function openJob(){ $('#jobModal').classList.remove('hidden') } $('#newJob').onclick=openJob;$('#newJob2').onclick=openJob;document.querySelectorAll('[data-close]').forEach(x=>x.onclick=()=>x.closest('.modal-backdrop').classList.add('hidden'));
$('#jobForm').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));const text=d.description.toLowerCase(),skills=(state.profile.skills||'').toLowerCase().split(/[,\n]/).filter(Boolean);const hits=skills.filter(s=>s.trim().length>2&&text.includes(s.trim())).length;const fit=Math.min(97,Math.max(62,70+hits*6));const keywords=['SQL','Power BI','Python','Excel','stakeholder management','data analysis'].filter(x=>text.includes(x.toLowerCase()));state.jobs.unshift({id:Date.now(),title:d.title,company:d.company,fit,ats:Math.max(65,fit-3),decision:fit>=80?'Apply':'Maybe',why:`Matched ${hits} skill${hits===1?'':'s'} from your truthful profile. The score reflects keyword overlap only; review the complete requirements before applying.`,keywords:keywords.length?keywords:['Review requirements']});save();e.target.reset();$('#jobModal').classList.add('hidden');nav('opportunities')};
window.showDetail=id=>{const j=state.jobs.find(x=>x.id===id);const prepared=state.applications.some(a=>a.id===id);$('#jobDetail').innerHTML=`<p class="eyebrow">JOB INTELLIGENCE REPORT</p><h2 class="detail-title">${j.title}</h2><p class="detail-company">${j.company}</p><div class="analysis"><div class="analysis-grid"><div>FIT SCORE<strong>${j.fit}/100</strong></div><div>ATS READINESS<strong>${j.ats}/100</strong></div></div><p class="reason"><strong>Recommendation: ${j.decision}.</strong> ${j.why}</p></div><p class="eyebrow">PRIORITY KEYWORDS</p><p class="reason">${j.keywords.join(' · ')}</p><p class="truth">Truthful-only protection: documents may only use information saved in your Career Profile. No qualifications or experience will be invented.</p><div class="action-row"><button class="button primary" onclick="prepare(${j.id})">${prepared?'Application prepared':'Prepare application'}</button><button class="button dark" data-close>Close</button></div>`;$('#detailModal').classList.remove('hidden');$('#detailModal [data-close]').onclick=()=>$('#detailModal').classList.add('hidden')};
window.prepare=id=>{const j=state.jobs.find(x=>x.id===id);if(!state.profile.headline){$('#detailModal').classList.add('hidden');nav('profile');return}if(!state.applications.some(a=>a.id===id)){state.applications.unshift({...j,date:new Date().toLocaleDateString('en-ZA')});save()}$('#detailModal').classList.add('hidden');nav('applications')};
$('#profileForm').onsubmit=e=>{e.preventDefault();state.profile=Object.fromEntries(new FormData(e.target));save();render();nav('command')};Object.entries(state.profile).forEach(([k,v])=>{const el=$(`[name="${k}"]`);if(el)el.value=v});render();
